import ArticlesPage from "@/features/Blog";
import { Metadata } from "next";
import React from "react";
export const metadata: Metadata = {
  title: "Gate of Africa - Articles",
  description: "Generated by create next app",
};
export default function AllBlog() {
  return <ArticlesPage />;
}
